### ISSUE TITLE
KMP Testing can't load libdynamic-linux-arm64-libsodium.so in initialization

### ISSUE THREAD

**Issue by RoyalSWiSH** [ionspin/kotlin-multiplatform-libsodium#48]
HI,

I try to initialize Libsodium from a test environment in a Kotlin Multiplattform project in the shared module from Android Studio.

```
import com.ionspin.kotlin.crypto.sample.EncryptionUtils
import com.ionspin.kotlin.crypto.secretbox.SecretBox
import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi
import kotlin.test.Test
import kotlin.test.assertContains
import kotlin.test.assertEquals
import com.ionspin.kotlin.crypto.LibsodiumInitializer
import kotlinx.coroutines.runBlocking


class EncryptionUtilsTest {


    @Test
    @OptIn(ExperimentalUnsignedTypes::class, ExperimentalEncodingApi::class)
    fun encryptMessageWithAssociatedDataTest() = runBlocking {
        LibsodiumInitializer.initializeWithCallback {
//                logger.info("Libsodium initialized")
        }
        val message = "Hello"
        val key = SecretBox.keygen()
        val encryptedMessage = EncryptionUtils.encryptMessageWithAssociatedData(message, key)
        val decryptedMessage = EncryptionUtils.decryptMessageWithAssociatedData(encryptedMessage, key)
        assertEquals(message, decryptedMessage)
    }
```

But it fails with this error

```
> Task :shared:testDebugUnitTest FAILED

java.lang.NullPointerException: Cannot invoke "java.net.URL.getFile()" because "url" is null
	at com.goterl.resourceloader.ResourceLoader.getFileFromFileSystem(ResourceLoader.java:244)
	at com.goterl.resourceloader.ResourceLoader.copyToTempDirectory(ResourceLoader.java:88)
	at com.goterl.resourceloader.SharedLibraryLoader.load(SharedLibraryLoader.java:53)
	at com.goterl.resourceloader.SharedLibraryLoader.load(SharedLibraryLoader.java:47)
	at com.ionspin.kotlin.crypto.LibsodiumInitializer.loadLibrary(LibsodiumInitializer.kt:19)
	at com.ionspin.kotlin.crypto.LibsodiumInitializer.initializeWithCallback(LibsodiumInitializer.kt:58)

```

My guess is, that it can't find the libsodium file in the testing environment here
```

    private fun loadLibrary() : JnaLibsodiumInterface {
        val libraryFile = when {
            Platform.isMac() -> {
                SharedLibraryLoader.get().load("libdynamic-macos.dylib", JnaLibsodiumInterface::class.java)
            }
            Platform.isLinux() -> {
                if (Platform.isARM()) {
                    SharedLibraryLoader.get().load("libdynamic-linux-arm64-libsodium.so", JnaLibsodiumInterface::class.java)
                } else {
                    SharedLibraryLoader.get()
                        .load("libdynamic-linux-x86-64-libsodium.so", JnaLibsodiumInterface::class.java)
                }
            }
            Platform.isWindows() -> {
                SharedLibraryLoader.get().load("libdynamic-msvc-x86-64-libsodium.dll", JnaLibsodiumInterface::class.java)
            }
            Platform.isAndroid() -> {
                File("irrelevant")
            }
            else -> throw RuntimeException("Unknown platform")

        }
```

**Comment by BernatCarbo** [comment]
Same here!

**Comment by ionspin** [comment]
I think the reason is that unit test are run on x86 and libsodium doesnt have a build for android on x86 (last time I checked, which was some time ago). You should see similar behavior if you try to run the library on x86 android emulator.

Should be fixable by expanding libsoidum to build android x86 target, but I don't have bandwith to look into it right now. A workaround is to skip android unit tests.

-------- Original Message --------

**Comment by RoyalSWiSH** [comment]
I run it on M3 Mac in Android Studio. Guess that is ARM.

**Comment by ionspin** [comment]
Yes, I guess on arm mac it should work, and you should be able to get it to work by replacing file in this:
'''
Platform.isAndroid() -> {
                File("irrelevant")
            }
'''
with 
'SharedLibraryLoader.get().load("libdynamic-macos.dylib", JnaLibsodiumInterface::class.java)'

I don't have access to a mac at the moment, so I can't test if that works correctly.

**Comment by BernatCarbo** [comment]
Interestingly, when using Windows, if I run a test from the common test source as Android(local) that calls `LibsodiumInitializer.initialize()`, it lands on `Platform.windows` so it tries to load `libdynamic-msvc-x86-64-libsodium.dll` and throws the same exception:
```
java.lang.NullPointerException: Cannot invoke "java.net.URL.getFile()" because "url" is null
	at com.goterl.resourceloader.ResourceLoader.getFileFromFileSystem(ResourceLoader.java:244)
	at com.goterl.resourceloader.ResourceLoader.copyToTempDirectory(ResourceLoader.java:88)
	at com.goterl.resourceloader.SharedLibraryLoader.load(SharedLibraryLoader.java:53)
	at com.goterl.resourceloader.SharedLibraryLoader.load(SharedLibraryLoader.java:47)
	at com.ionspin.kotlin.crypto.LibsodiumInitializer.loadLibrary(LibsodiumInitializer.kt:30)
	at com.ionspin.kotlin.crypto.LibsodiumInitializer.initialize(LibsodiumInitializer.kt:52)
```

**Comment by XantreDev** [comment]
There is similar error on MacOS M1 chip
```
    java.lang.NullPointerException: Cannot invoke "java.net.URL.getFile()" because "url" is null
        at com.goterl.resourceloader.ResourceLoader.getFileFromFileSystem(ResourceLoader.java:244)
        at com.goterl.resourceloader.ResourceLoader.copyToTempDirectory(ResourceLoader.java:88)
        at com.goterl.resourceloader.SharedLibraryLoader.load(SharedLibraryLoader.java:53)
        at com.goterl.resourceloader.SharedLibraryLoader.load(SharedLibraryLoader.java:47)
        at com.ionspin.kotlin.crypto.LibsodiumInitializer.loadLibrary(LibsodiumInitializer.kt:19)
        at com.ionspin.kotlin.crypto.LibsodiumInitializer.initialize(LibsodiumInitializer.kt:52)
 ```
